beer-garden/functionary

functionary/builder/api/v1/views/publish.py, functionary/builder/models/build.py, functionary/builder/utils.py, functionary/core/admin/__init__.py, functionary/core/api/v1/serializers/team.py, functionary/core/models/__init__.py, functionary/core/models/environment.py, functionary/core/models/function.py, functionary/core/models/package.py, functionary/core/models/team.py, functionary/functionary/settings/django_.py, functionary/requirements.in, functionary/requirements.txt
Closes #18 
This PR establishes the Environments model and replaces most references to a Team with an association to an Environment instead.  Other changes of note:
* The Team model has been updated to create a default environment when a Team is created.
* The `/api/v1/teams` endpoint now returns a list of environments for the team.
* The `/api/v1/publish` endpoint now accepts an X-Environment-Id *or* an X-Team-Id.  If only X-Team-Id is provided, the environment is set to the default environment for that Team.  This interaction will be generalized in a future PR (the logic for this does not belong on individual endpoints).
=> #18 - Add Environments

functionary/builder/api/v1/views/publish.py, functionary/core/api/mixins.py
Closes #20 
This PR adds a mixin to handle the X-Team-Id and X-Environment-Id headers so that the logic can be reused across all of the relevant views.
=> Created EnvironmentViewMixin to centralize request environment handling

cli/functionary/login.py, cli/functionary/package.py, cli/functionary/tokens.py, functionary/builder/utils.py
Closes #17 
-The login command now hits the /api/v1/api-token-auth endpoint to retrieve the token.
-The header that gets set to use the token prefixes the token with "Token" rather than "Bearer"
-The package tarball puts the files at the root of the structure rather than nested in a subdirectory
--The package tarball is sent to /api/v1/publish and the request includes the X-Environment-Id header.
=> #17 - Update CLI login and publish commands

.github/workflows/linters.yml, functionary/builder/utils.py
This PR changes the github action to run isort on the directories individually rather than all at once to fix an issue where "docker" was being treated as a first party module, since there is a "docker" folder at the root of the repo.
=> Fix first party module issue in isort github action

functionary/core/auth/__init__.py, functionary/core/auth/backends.py, functionary/core/models/user_role.py
This PR fixes the Enum names in core.auth to be singular rather than plural, to better follow standard conventions.
=> Correct auth Enum names to be singular

functionary/README.md, functionary/builder/api/v1/views/build.py, functionary/core/api/mixins.py, functionary/core/api/v1/views/function.py, functionary/core/api/v1/views/package.py, functionary/core/api/v1/views/team.py, functionary/core/api/v1/views/user.py, functionary/core/api/viewsets.py
Closes #34 
This PR adds `EnvironmentModelViewSet` and `EnvironmentReadOnlyModelViewSet`, which are intended to be used in place of the DRF `ModelViewSet` and `ReadOnlyModelViewSet` in situations where the ViewSet's queryset should be filtered to objects belonging to the request's environment context.  The following functionality is provided:
* The queryset is automatically filtered to the correct objects for the environment.
* If the relationship to an environment is indirect (i.e. The `Function` model has an environment through it's associated package), that can be defined via the `environment_through_field` attribute.
* The environment and team header parameters are included so that they do not have to be explicitly added to ViewSets building off of these new ones.
* Create packages, …
=> #34 - Environment ViewSets

functionary/builder/api/v1/views/build.py, functionary/builder/api/v1/views/publish.py, functionary/core/api/mixins.py, functionary/core/api/permissions.py, functionary/core/api/v1/views/execute.py, functionary/core/api/v1/views/function.py, functionary/core/api/v1/views/package.py, functionary/core/api/v1/views/team.py, functionary/core/api/v1/views/user.py, functionary/functionary/settings/rest_framework_.py
Closes #37 
This PR does the following:
* Sets the drf `DEFAULT_PERMISSION_CLASSES` to `isAuthenticated`.  Any views that intend to use that as their permission class no longer have it explicitly defined.
* Adds a `HasEnvironmentPermissionForAction` permission class for use on viewsets that inherit build off of the `EnvironmentViewMixin` mixin in some way.  This class determines the permission needed for the request and then grants or denies access based on the user's permissions.
* The `ExecuteView` remains untouched for now.  Although it falls into the same category as `PublishView`, that is going to change soon as we move that logic over to a `TaskViewSet`.  The permissions enforcement will be added then.
* Create a non-admin user.  Do not assign it any user roles.
* Hitting the …
=> #37 - Environment based permission class for views

cli/functionary/environment.py, cli/functionary/functionary.py, cli/functionary/package.py
Closes #28 
Created new environment.py file that has a get and a set command, storing the current environment in the config file. Changed publish to use the new config file value instead of us exporting through the command line.
Original issue had wondered about creating an alias so that environment and env would go to the same list of commands. I did a little searching and it doesn't look like Click supports this out of the box, but there do seem to be a few libraries that support it that we could import (like this one for example: [https://pypi.org/project/click-aliases/](url)
=> #28: CLI - Add env set and list

functionary/core/api/v1/serializers/team.py, functionary/core/api/v1/views/team.py, functionary/core/models/user_role.py
Closes #41 
This PR adds filtering on the `/api/v1/teams` endpoint to only show the teams and environments to which a user belongs.  The behavior is now this:
* If the user is a superuser, all teams and environments will be shown.
* If the user has a role on a team, that team and all of its environments will be shown.
* If the user has a role on an environment, that environment's team will shown, but only the environments that the user has a role on will be shown for that team.
There's also a fix to the unique constraint on user roles.  The intent was that a user should have only a single role assigned per team or environment.  That is now properly enforced.
=> #41 - Filter team endpoint based on user roles

cli/functionary/client.py, cli/functionary/environment.py, cli/functionary/package.py, cli/functionary/utils.py, cli/requirements.txt, cli/setup.py
Closes #47 
I have added a buildstatus command into package.py. This uses the rich library (which you'd need to install with pip install rich) to turn API data into a nice table. I've written a helper function called _format_results to turn a list of dictionaries into a Rich table. That function currently lives in package.py but it could live somewhere else if we'd rather.
Also, I changed environment list to have the active environment marked in red. Could change that color if needed.
=> Issue 47: Adding buildstatus and table output

functionary/README.md, functionary/builder/utils.py, functionary/core/celery.py, functionary/core/management/commands/run_worker.py, functionary/core/models/__init__.py, functionary/core/models/mixins.py, functionary/core/models/task.py, functionary/core/models/team.py, functionary/core/utils/messaging.py, functionary/core/utils/tasking.py, functionary/functionary/settings/__init__.py, functionary/functionary/settings/logging_.py, functionary/functionary/settings/rabbitmq_.py, functionary/requirements.in, functionary/requirements.txt, runner/README.md, runner/main.py, runner/runner/celery.py, runner/runner/handlers.py, runner/runner/listener.py, runner/runner/message_queue.py
Closes #56 
This PR adds message publishing to the RabbitMQ broker when a Task instance is created.  This is done via a `post_create` hook on the Task model.
There are also a lot of incidental changes both directly and indirectly related to that.  Comments will be provided on specific lines in the PR.
* The READMEs have been updated to include instructions on how to configure the RABBITMQ username and password, as well as how to start the worker and runner processes.  Try following those instructions to ensure that they are accurate.
* Once everything is running, create a new Task.
* You should see the runner listener pick up the message and had it over to the runner celery worker, which will execute the tasking and publish a message with the results.  This should be visible in the logs, …
=> Task Execution

functionary/builder/api/v1/serializers/package_definition.py, functionary/builder/utils.py, functionary/core/models/task.py, functionary/ui/forms/forms.py, functionary/ui/static/css/functionary.css, functionary/ui/templates/forms/task_parameters.html, functionary/ui/templates/unicorn/task_detail.html, functionary/ui/views/functions.py
This PR adds support for the following datatypes:
- string (assumed short input)
- text (longer form input)
- integer
- float
- boolean
- date
- datetime
- json
The json field is parsed and validated that it is json. This allows for object or lists of JSON supported types to be passed to the function.
All the fields are validated to be of the correct datatype and the page will display error messages below the failing fields.
This was tested by making a function with all the possible parameter types and printing the value received by the function in the docker runner.
=> Add additional parameter types.

cli/functionary/login.py
Closes #65 
Really simple change that just stores the host after the login function successfully runs. I want to say that the host not being in the same section of code as the token was a holdover from the time I was trying to make the login use the same centralized get/post commands as everything else
=> Issue 65: change save host line location

cli/functionary/package.py, cli/functionary/templates/package.yaml, examples/calculator/package.yaml, functionary/builder/api/v1/serializers/package_definition.py, functionary/builder/utils.py, functionary/core/models/function.py, functionary/core/models/package.py, functionary/ui/templates/core/environment_detail.html, functionary/ui/templates/core/function_detail.html, functionary/ui/templates/core/function_list.html, functionary/ui/templates/core/package_detail.html, functionary/ui/templates/core/package_list.html
This PR adds optional fields for summary for both Packages and Functions. 
The calculator example is updated with the new summary field, the template has a stub for the summary field also. The database has the new optional summary field and the UI has been updated to show the summary on the Package/Function lists as well as the Environment details. Package/Function description is shown on their details page.
The CLI create command was updated to prompt for language if that required option was missing from the command line.
=> Issue 73: add summary field for package and function

docker/docker-compose.yml, functionary/functionary/settings/__init__.py, functionary/functionary/settings/base.py, functionary/functionary/settings/debug.py, functionary/functionary/settings/prod.py, functionary/functionary/urls.py, functionary/requirements-dev.in, functionary/requirements-dev.txt, functionary/requirements.txt, setup.cfg
Closes #82 
This PR adds the Django Debug Toolbar as part of the new debug settings module. Settings modules now inherit from a `base.py` module, which instantiates all the default values. A separate module file can then import all the module-level variables from `base.py` and overwrite them as necessary.
- In `docker-compose.yml`, edit the `DJANGO_SETTINGS_MODULE` to point to whichever settings file you want to use
- If using the `debug` settings module, visit Functionary's UI and verify the Django Debug Toolbar is available on the right-side of the screen
=> #82 - Added django debug toolbar

cli/functionary/package.py, cli/functionary/utils.py, functionary/builder/api/v1/serializers/build.py, functionary/builder/api/v1/views/build.py, functionary/builder/models/build.py, functionary/builder/utils.py
This PR updates the build process to save the initial package definition and parses all the functions before starting the build process. This will allow all builds to have a link to a package, regardless of the initial build success/failure. As the build progresses, the build status will be set appropriately and on success, the package is updated with the rest of the new information in the just-built package and the functions are also saved.
The build serializer was updated to return the package name and creator name vs. IDs to display meaningful information for the `buildstatus` command.
=> 77-Update build endpoint.

functionary/builder/api/v1/views/publish.py, functionary/builder/exceptions.py, functionary/core/api/exceptions.py, functionary/core/api/mixins.py, functionary/functionary/settings/base/rest_framework_.py
Closes #98 
First draft of outfitting the 400 errors with error codes by adding a new exception handler (defined in core/api/exceptions.py for use in settings file functionary/settings/base/rest_framework.py). Current exceptions are InvalidPackage (for package yaml errors, defined in builder/exceptions.py for use in builder/api/v1/views/publish.py ), MissingEnvironmentHeader, InvalidEnvironmentHeader, InvalidTeamIDHeader (all defined in core/api/exceptions.py for use in core/api/mixins.py).
I left BadRequest defined in core/api/exceptions.py, but replaced it with the other exceptions wherever else it is in the code. Left error messages mostly the same
=> Issue 98: Add codes to 400 errors

docs/VSCODE.md, functionary.code-workspace, functionary/core/fixtures/bootstrap.yaml, functionary/init.sh
This PR builds on the initial work for #79.  It fleshes out the fixture data so that it now contains
* Two separate Teams:
* FunctionFoundry, containing a dev and prod environment
* ScriptSanctuary, containing just a default environment
* A bunch of users with various roles for FunctionFoundry:
* admin: The same superuser account that existed before
* ff-admin: admin role for the entire team
* ff-readonly: read only role for the entire team
* ff-developer: developer role for dev
* ff-operator: operator role for prod
* The password for all users is the same as their username
The idea is just to have a handful of accounts ready to go with different permissions to easily test or demonstrate access control in various areas.
Additionally, I added a dependent task that starts the django …
=> #79 - Added additional fixture data

cli/functionary/package.py, cli/functionary/parser/__init__.py, cli/functionary/parser/python.py
Closes #62 
First draft attempt to populate the yaml automatically. I'm using the inbuilt python libraries inspect and importlib.util to import the module the user passes in and parse the module/function objects that inspect returns. At the end, I'm replacing a placeholder in the yaml with the json.dumps (though it's a little awkwardly formatted when it shows up on the yaml, so that's an area I could use some tips on)
=> Issue 62: Add functions dynamically to yaml

docker/docker-compose.yml, runner/.vscode/.debug.env, runner/runner.py, runner/runner/celery.py
Closes #92 
This PR removes the Redis dependency from the Runner by using the Filesystem broker for Celery.
- Celery App for the Runner uses the Filesystem broker instead of the Redis broker
- Start Functionary
- Inspect container logs for `functionary_runner`. In the config section of the Celery startup message, it should say Celery is using `filesystem://localhost//` for the `transport` variable
- You should also see Celery repeatedly checking for new tasks every second
- Run a Functionary function to verify function gets executed as expected
=> #92 - Runner now uses filesystem broker instead of redis

cli/functionary/utils.py
Closes #106 
Makes datetime objects present in cli tables come out formatted like '2022-10-13 19:36:18UTC'
=> #106: Remove milliseconds from datetime display

cli/tests/test_parse.py
Closes #107 
Added some tests for python parsing using genschema. This draft has tests for all the different arg types and a few extras for nonstandard args. On this draft, I'm setting up a pytest fixture that uses tmp_path to create a yaml. We'll use the yaml on each of the tests, create a functions.py based on whatever we we want to test, then use CliRunner to simular calling genschema on that functions.py. I have assert functions that check that the generated package.yaml looks like how it should for each of the tests.
Could be too many tests or not enough tests.
=> #107: Add unit tests for python parsing

functionary/ui/templates/base.html, functionary/ui/templates/builder/build_detail.html, functionary/ui/templates/builder/build_list.html, functionary/ui/urls.py, functionary/ui/views/builds.py
Closes #124 
Added two new templates: functionary/ui/templates/builder/build_list.html and functionary/ui/templates/builder/build_detail.html. Two new corresponding views to go with them in functionary/ui/views/builds.py. Updated functionary/ui/urls.py with routes to the new views.
The one minor thing I saw to add was making the newline characters in the log print out. The editor didn't seem to like it style wise if I did it using inline styles on the html page, but the css file involved here looks like a ton of preset stuff.
=> Issue 124: Add build viewing to UI

docker/docker-compose.yml, functionary/core/utils/scheduling.py, functionary/ui/forms/tasks.py, functionary/ui/templates/base.html, functionary/ui/templates/core/scheduled_task_create.html, functionary/ui/templates/core/scheduled_task_list.html, functionary/ui/templates/core/scheduled_task_update.html, functionary/ui/templates/partials/crontab_invalid.html, functionary/ui/templates/partials/function_parameters.html, functionary/ui/urls.py, functionary/ui/views/scheduling.py, functionary/ui/views/view_base.py
Closes #114 
- Added scheduled task list, create, and update pages
- Dynamically load function parameters with htmx
- Dynamically validate crontab fields with htmx
- Added separate htmx urls
- Display message to user if they have no scheduled tasks they can make in their current environment
- Display form errors when creating or updating a `ScheduledTask`
- Launch Functionary and view the `Scheduling` UI
- Create tasks and verify they run according to the crontab schedule
- Update tasks to verify their next run reflects those updates
- Try and submit invalid data to the forms and verify you receive an error
- There are some helper functions in `core.utils.scheduling` that I think can be migrated over to the `ScheduledTask` model
- With my current implementation, I do not persist parameter …
=> #114 - Scheduled Tasking frontend support

functionary/ui/templates/core/task_detail.html, functionary/ui/templates/core/task_list.html, functionary/ui/templates/partials/output.html, functionary/ui/templates/partials/pagination_navbar.html, functionary/ui/templates/partials/task_element.html, functionary/ui/templates/partials/task_log.html, functionary/ui/templates/partials/task_result.html, functionary/ui/templates/partials/task_result_block.html, functionary/ui/templatetags/paginator.py, functionary/ui/urls.py, functionary/ui/views/tasks.py
Closes #141 and #142 
- Added pagination navbar to the `TaskList` 
- Created a pagination navbar partial so it can be re-used in other lists views
- Added button to `TaskDetail` to view the Task logs after the task has finished processing
- View the `TaskList`, verify the pagination navbar is visible at the bottom
- View the `TastDetail`, wait for a task to finish executing, verify clicking the button to view logs returns the logs if they exist
=> #141 - Added pagination to TaskList, added ability to get task logs

functionary/builder/celery.py, functionary/core/celery.py, functionary/core/utils/tasking.py, runner/runner.py, runner/runner/celery.py, runner/runner/handlers.py, runner/runner/listener.py, runner/runner/logging_configs.py
Closes #95 
This PR adds a consistent format for logs produced by the Django and Celery applications. 
- Added logging dictionary config in `functionary/settings/base/__init__.py` that configures the various loggers
- Added logging dictionary config in `functionary/settings/base/celery_.py` that configures the Celery logger 
- Added environment variable to disable the `Pika` logs in the `runner-worker` and `runner-listener`
- Spin up Functionary
- Inspect the logs of any Functionary containers
- Verify the outputted log format matches the logging format defined in the `LOGGING` config
- For Django apps: `functionary/settings/base/__init__.py`
- For Celery: `functionary/settings/base/celery_.py` or in the `celery.py` file that defines the Celery app
=> #95 - Added consistent formatting to all loggers

functionary/core/models/scheduled_task.py, functionary/core/utils/scheduling.py, functionary/ui/forms/tasks.py, functionary/ui/views/scheduling.py
This PR does 3 tangentially related things
* Updates `TaskParameterForm` to allow for the proper setting of initial values, and to have a prefix on the form parameter fields so that they are not as easily conflicted when used in conjunction with other forms.
* The above bullet allows for the removal of some of the duplicative form handling logic related to the parameter portion of the ScheduledTask creation / update, instead just leveraging the `TaskParameterForm`.
* Removes the app cross-contamination that was introduced in ScheduledTask (code from the ui app being referenced in the core app).  It also tries to streamlining some things in the process by converting some of the utility functions over to methods that are native to the model.
There is some additional cleanup that needs to …
=> ScheduledTask / TaskParameterForm cleanup

functionary/ui/templates/core/function_detail.html, functionary/ui/views/functions.py
While trying to fix a previous layout issue when a user didn't have permissions to task a function, the execute button was accidentally hidden for functions without parameters. This shows the button properly.
The old code for displaying the now defunct `output_format` for functions was also removed.
=> Fix the missing execute button on some functions.

functionary/.vscode/launch.json
Adds a vscode debug launcher for the django shell so that it's easier to do some debugging via an interactive shell.
=> Add a vscode debug task for the django shell

functionary/ui/forms/__init__.py, functionary/ui/forms/scheduled_task.py, functionary/ui/forms/tasks.py, functionary/ui/views/scheduling.py
This PR does two things:
* Moves ScheduledTaskForm into its own file
* Makes it possible to override the field type mapping in TaskParameterForm, in preparation for some work to come related to Workflows.
* Verify that it is still possible to create / edit scheduled tasks.
* NOTE: There are some bugs related to scheduled tasks (json fields do not work, warning message displays twice, maybe others), but there should be no new bugs introduced by this change.
=> Move ScheduledTaskForm to its own file

functionary/core/models/scheduled_task.py, functionary/core/models/task.py, functionary/core/utils/serialization.py, functionary/ui/forms/tasks.py, functionary/ui/templates/core/scheduled_task_create.html, functionary/ui/templates/core/scheduled_task_list.html, functionary/ui/templates/core/scheduled_task_update.html, functionary/ui/urls.py, functionary/ui/views/functions.py, functionary/ui/views/scheduling.py, functionary/ui/views/tasks.py
Closes #161 
- Added new util to handle serialization of python dictionaries to JSON strings
- This utility is used to create a new dictionary of a Task or ScheduledTask parameters, which is what the JSON Schema Validator will use to validate the parameters conform to the function's schema
- Removed the `_prepare_initial_value` function in the Tasks.py since it was really only ever looking for a JSON field to run `loads`. Now, in the `__init__()` of the `TaskParameterForm`, the form just uses the value from initial.
- Added some missing type hints
- Fixed some linting complaints
- Fixed missing ScheduledTask url for form submission
- Removed `obj = *.objects.create()` in favor of `obj = Object() -> obj.clean()  -> obj.save()`
- Removed extra message display in ScheduledTask list in favor …
=> #161 - Fixed serialization issues during validation

functionary/ui/forms/__init__.py, functionary/ui/forms/tasks.py, functionary/ui/forms/workflow_step.py, functionary/ui/templates/core/scheduled_task_update.html, functionary/ui/templates/core/workflow_detail.html, functionary/ui/templates/forms/workflows/step_edit.html, functionary/ui/templates/partials/workflows/step_list.html, functionary/ui/tests/forms/test_tasks.py, functionary/ui/urls.py, functionary/ui/views/functions.py, functionary/ui/views/scheduling.py, functionary/ui/views/workflows/__init__.py, functionary/ui/views/workflows/steps/create.py, functionary/ui/views/workflows/steps/delete.py, functionary/ui/views/workflows/steps/update.py
Continues #143 
This PR adds the ability to create, delete, and edit workflow steps.  Some related things that happen in this PR:
* Created TaskParameterTemplateForm, a variant of TaskParameterForm that accepts template variables as input in addition to the field type.
* Updated the "function_parameters/" endpoint to take an optional "allow_template_variables" parameter, which decides which variant of the TaskParameterForm gets used.
* Because "function_parameters/" is no longer ScheduledTask specific, it has been relocated to a more appropriate, general location.
* The bit in "function_parameters" that derives the existing parameters so that it can populate the form fields for existing scheduled tasks has been removed.  Instead, the template for updating scheduled tasks just includes the …
=> #143 - Workflow Steps UI

functionary/core/models/workflow_step.py, functionary/core/utils/workflow.py, functionary/ui/templates/partials/workflows/step_list.html, functionary/ui/tests/views/workflows/steps/test_update.py, functionary/ui/urls.py, functionary/ui/views/workflows/__init__.py, functionary/ui/views/workflows/steps/update.py
Continues #143
This PR adds the ability to move workflow steps up or down, one step at a time.  Once again, the UI is entirely function over form, as it just aims to show how the calls to perform the actions should work, with the intent that someone will come back through and make it look pretty later.
* Add several steps to a workflow
* In the Steps section of the workflow detail page, click the up and down arrows at the front of the step rows and verify that the steps move as expected.
* Unit tests have been added for the "workflowstep-move" endpoint and all of the responses it is expected to return.
=> #143 - Reorder workflow steps

functionary/core/models/user.py, functionary/ui/templates/core/workflow_list.html, functionary/ui/templates/forms/environment_selector.html, functionary/ui/templates/home.html, functionary/ui/tests/views/test_environment_select.py, functionary/ui/tests/views/test_utils.py, functionary/ui/urls.py, functionary/ui/views/environment_select.py, functionary/ui/views/environments/__init__.py, functionary/ui/views/environments/list.py, functionary/ui/views/environments/update.py, functionary/ui/views/home.py, functionary/ui/views/utils.py, functionary/ui/views/workflows/list.py
Closes #172 
The main objective of this PR is to add the user's environment permissions to the session data so that it is always available for use in the context for a template.  With no other setup, you can do something like this in a template:
```
{% if request.session.user_can_create_task %}
```
These `user_can_<action>_<model>` session variables are populated whenever the environment is switched, or via the "home" view that a user is directed to at login.
As part of the changes here, a bunch of other incidental changes were made to the surrounding code.  Namely:
* The `EnvironmentSelectView` was moved into its own file, rather than being lumped in with the views related to the Environment model, since it's really dealing with a different thing.
* The path for the view was changed as …
=> #172 - Make user permissions available in the session data

functionary/core/management/commands/run_scheduler.py
Closes #169 
- Decreased Scheduler's WakeUp Sync Interval
- This interval is how often the Scheduler queries the DB to figure out which `PeriodicTask`s have been updated. More specifically, which `PeriodicTask`s status' have been updated
- The caveat with the solution is that if the problem will always exist, its just a matter of how often we want the Scheduler to re-sync with the DB. In this PR, I opted to let it re-sync every 5 seconds. So if I activate, pause, or archive the ScheduledTask when there is less than 5 seconds left before the task is scheduled to run, the task will follow whatever state it was prior to me submitting the updated status.
Activate a previously paused or archived ScheduledTask and verify the ScheduledTask runs when expected
=> #169 - Decreased scheduler wakeup sync delay

functionary/builder/tests/test_utils.py, functionary/builder/utils.py, functionary/ui/views/functions.py
Fix to #183 
This fixes a logic bug during the package build that was resulting in all functions for packages other than the one being published getting deactivated.  Now the logic to find which functions to deactivate is properly scoped to the package being published instead.
* The unit test for function deactivation has been overhauled to properly capture what we're trying to test: Only functions for the package being published that are not present in the package.yaml get deactivated.  All others remain active.
* To manually test, publish a package, then publish another one.  The functions from the first published package should still be active even after the second one is published.
=> #183 - Fix package build function deactivation

functionary/core/management/commands/run_scheduler.py, functionary/core/management/commands/utils.py
Closes #198 
- Added a util command for the management commands that will attempt to run the given command
- The command will be re-run on a delay if the necessary migrations have not been run
- Clear your database volume
- Start functionary
- The scheduler container should not be in a stopped state and claim that the necessary migrations have not been run yet
- Apply the migrations
- The scheduler container will start working as intended once it detects the migrations
=> #198 - Added util command to not crash while migrations get loaded

functionary/core/utils/minio.py, functionary/ui/views/function.py
Closes #204 
- Throw appropriate exceptions when initializing the MinIO Client
- `MaxRetryError` when the client is unable to connect to the MinIO instance
- `S3Error` when client is unable to authenticate the with the MinIO instance
- Since you cannot use the MinIO client without first initializing the client, then this should prevent downstream client exceptions when a connection to MinIO cannot be established
- Change the S3 Access Key or Secret key to something other than the Access Key and Secret Key that establishes the MinIO Root User
- Start Functionary
- Use the `Number of Files` function and try to submit a file
- A non-field error should appear claiming that functionary was unable to authenticate with the S3 provider
- Stop the MinIO container and re-submit the file
- The page …
=> #204 - Added S3 error handling to function detail view

functionary/core/models/scheduled_task.py, functionary/core/tests/utils/test_parameter.py, functionary/core/utils/parameter.py, functionary/ui/forms/scheduled_task.py, functionary/ui/templates/core/scheduledtask_detail.html, functionary/ui/templates/forms/scheduled_task/scheduled_task_edit.html, functionary/ui/views/scheduled_task/create.py, functionary/ui/views/scheduled_task/update.py
Closes #196 
This PR allows Functionary to schedule functions that don't have parameters.  It also updates the ScheduledTask model to create PeriodicTasks with the ScheduledTask's id instead of name and adds an edit button the the ScheduledTask details page.
Testing:
Try create a scheduled task that takes JSON input. Put invalid JSON in the field so validation fails.  Check that there is only one error shown at the field instead of at the top of the form.
Create another similar task with invalid JSON, but also add an invalid character for one of the cron fields. Ensure both errors are shown on the form and nothing at the top. When you correct the JSON, verify that the cron error is still shown.
=> Allow scheduling functions without parameters.

functionary/functionary/settings/debug.py, functionary/functionary/settings/local_settings.py
This PR updates the `debug.py` settings to attempt to import from `local_settings.py`if available. Out of the box, this will add all new entries to the `django.conf.settings` with whatever values are in the `local_settings.py`. Any matching values will be overridden.
=> Import local.py for additional settings if present

examples/demo/functions.py, examples/demo/package.yaml, functionary/core/api/exceptions.py, functionary/core/api/v1/serializers/task.py, functionary/core/api/v1/utils.py, functionary/core/api/v1/views/task.py, functionary/core/tests/api/v1/views/test_task.py, functionary/core/tests/api/v1/views/test_text.txt
Closes #213 
- The `/api/v1/tasks` endpoint now handles file input in the same way as the UI
- The only caveat is that you cannot submit Tasks that rely on file parameters through the Swagger UI
- Publish the demo package to Functionary
- Fetch an authentication token from the API
- `curl -X POST http://localhost:8000/api/v1/api-token-auth -H 'accept: application/json' -F "username=" -F "password="`
- Submit a task to the `num_chars_api` test function
- `curl -X POST http://localhost:8000/api/v1/tasks/ -H 'accept: application/json' -H 'X-Environment-Id: <env uuid>' -H 'Content-Type: multipart/form-data' -F "function=<function uuid>" -F "file.function=@/path/to/file" -F 'parameters={"other_param": "hello world"}' -H "Authorization: Token <your auth token>"`
- Verify task runs as expected
=> #213 - Added file param support for the API

functionary/ui/forms/tasks.py, functionary/ui/tests/views/test_function.py
Closes #224 
This PR fixes optional parameter handling so that fields left blank on the tasking form are not saved as part of the Task parameters.  The prior behavior resulted in every parameter being included, with those that were blank on the form getting set to the Field class's `empty_value`, which is either `None` or `""` depending on the field type.
Note: boolean fields will always be included.  The empty value for a boolean is `False`, which makes sense, since that field being left blank on the form implies a value of `False`.
A unit test has been added to ensure the proper behavior.  This can be easily manually tested by running the "long running process" example function and trying to execute with no value set for duration.  Previously this would result in a validation error. …
=> #224 - Fix optional parameter handling when tasking through the UI

functionary/functionary/settings/base/__init__.py, functionary/ui/templates/forms/environment_selector.html, functionary/ui/templates/partials/env_selector.html, functionary/ui/tests/views/test_environment_select.py, functionary/ui/tests/views/test_utils.py, functionary/ui/views/environment_select.py, functionary/ui/views/utils.py
This PR updates the handling of the environment selector drop down so that it doesn't flash in and out as it's re-rendering on every page load.
What I've done is moved the logic that was in `EnvironmentSelectView` into a context processor so that the user environment data gets stamped into the context automatically (whenever `get_context_data()` is called).  That lets us get out of having to do the lazy load of the environment selector and can instead just render it directly as part of the main template rendering.
* Note the current behavior of the env selector dropdown flashing in and out as you change pages.
* On this branch that should no longer be the case.
=> Fix environment selector rendering

functionary/core/api/v1/views/task.py, functionary/core/tests/api/v1/views/test_task.py, functionary/core/utils/minio.py, functionary/ui/tests/views/test_function.py, functionary/ui/views/function.py
Closes #241 
- Added a `S3FileUploadError` exception
- Raised when `client.put_file` raises any exception
- API and UI return an error claiming that the file(s) were not able to be uploaded with a status of `503`
- Added unit tests for API and views
- To manually test, simply raise the `S3FileUploadError` before the `client.put_file` in `minio.py` to view the errors that get returned or rendered
=> #241 - Added failed file upload error handling

functionary/ui/static/css/functionary.css
Closes #248 
This PR adds some css styling to the already present "asc" and "desc" classes so that an indicator gets displayed on the column headers to show the current sorting.
* Go to any of the list views and sort.  You should see an indicator showing which way the sort is going.  Tasking and Builds are sorted by their date columns by default, so those show indicators even on the initial load.
=> 248 - Add inidicator for how the tables are sorted

cli/.vscode/launch.json, cli/functionary/functionary.py, cli/functionary/package.py, cli/tests/test_package.py
This PR adds the option of -k or --keep to the publish command which will result in the demo tar file being stored in ~/.functionary/builds/. If the publish command is ran without the option (-k/--keep) it will simply be cleaned up after the operation is finished.
` functionary package publish examples/demo` - Should result the tar file being cleaned up
`functionary package publish examples/demo --keep` - Should result in a tar file being stored in the ./functionary/builds/ folder
In addition 2 tests added to test_package.py
=> 179 Cleanup package tarball

functionary/ui/forms/workflow_step.py, functionary/ui/scss/custom.scss, functionary/ui/static/css/custom_bootstrap.css, functionary/ui/templates/account/login.html, functionary/ui/templates/builder/build_detail.html, functionary/ui/templates/core/package_detail.html, functionary/ui/templates/core/task_detail.html, functionary/ui/templates/core/workflow_detail.html, functionary/ui/templates/forms/workflow/parameter_edit.html, functionary/ui/templates/forms/workflow/step_edit.html, functionary/ui/templates/forms/workflow/workflow_edit.html, functionary/ui/templates/partials/modal.html, functionary/ui/templates/partials/table.html, functionary/ui/templates/partials/workflows/parameter_list.html, functionary/ui/templates/partials/workflows/step_list.html, functionary/ui/views/workflow/detail.py
Does not close ticket, still further work to do.
Converts Workflow detail page into bootstrap. All functionality on the page should work and by styled, including modals. Step table rows can be sorted with up/down arrows. Made a note on the UI ToDo to look into drag/drop as alternate for table row arrows.
Added missing breadcrumbs to Workflow Detail page. A little code cleanup / remove necessary classes.
Main title icon seemed excessively large - decreased size. Changed a few buttons to `primary` from `success` color.
=> #201 - workflow detail

functionary/builder/api/v1/serializers/package_definition.py, functionary/builder/api/v1/urls.py, functionary/builder/api/v1/views/publish.py, functionary/builder/tests/test_utils.py, functionary/builder/tests/views/test_publish.py, functionary/builder/utils.py
Closes #222 
- Added more `try`/`excepts` to parts of the `extract_package_definition` method in the builder
- Handle the YAML parse issues to prevent `500` error. Now returns a `400`
Create a new package with a malformed package.yaml:
```yaml
version: 1.0
package:
name: "invalid"
display_name: Functionality Demo
summary: Provides functions that demo / test various available features
language: "python"
functions:
- name: output_json
summary: Demonstrates JSON output rendering
display_name: Output JSON
description:
'Takes in a JSON blob and then simply returns that to demonstrate how
the JSON rendering works in the UI. To see table rendering, the input
should be a list formatted something like: [ { "param1": "value1",
"param2": "value2" }, { "param1": "value3", "param2": "value4" } ]' …
```
=> #222 - Added error handling to package yaml extraction

functionary/ui/templates/account/details.html, functionary/ui/templates/base.html, functionary/ui/templates/partials/socialaccount/connections.html, functionary/ui/templates/partials/token.html, functionary/ui/templatetags/social_helper.py, functionary/ui/tests/views/test_account.py, functionary/ui/urls.py, functionary/ui/views/account.py
This PR adds the ability to see and refresh the users token. This is useful if the user needs to remove a compromised token, or if you need to get a login token to make API calls over HTTP.
This change involved moving the social account connections page to a partial and adding a new account details page that also shows the token.  The social account delete view from django-allauth had to be circumvented because it would always redirect to a fixed URL instead of listening to the `next` parameter.
Closes #251
=> Added ability to refresh the login token.

functionary/core/api/v1/serializers/__init__.py, functionary/core/api/v1/serializers/task.py, functionary/core/api/v1/utils.py, functionary/core/api/v1/views/task.py, functionary/core/tests/api/v1/views/test_task.py, functionary/core/utils/tasking.py
Closes #264 
This PR fixes tasking via the API by ensuring that the input parameters are properly deserialized.  Things happening here:
* It is no longer possible to provide the tasking parameters as a single `parameters` field with a json string.  This was incompatible with file tasking and managing both styles added needless complexity both from an implementation perspective and in communicating in the documentation how the endpoint works.  Now all function or workflow parameters *must* be provided as individual fields, prefixed with `param.` .
* Unexpected input now returns a 400 error.  This is to prevent situations where someone intends to provide an optional parameter and leaves off the `param.`, or mistypes the parameter as something like `param.inupt` instead of `param.input`. …
=> #264 - Fix Tasking via API

functionary/ui/tests/views/environment/test_environment_utils.py, functionary/ui/tests/views/team/test_team_utils.py, functionary/ui/views/environment/detail.py, functionary/ui/views/environment/user_role/create.py, functionary/ui/views/environment/user_role/update.py, functionary/ui/views/environment/utils.py, functionary/ui/views/team/detail.py, functionary/ui/views/team/utils.py
The current `get_users()` calls for Team and Environment detail pages query for all users multiple times. This PR updates the call to query once for everything that's needed for the call and return the appropriate values.
=> Refactor get_users to reduce database calls.

functionary/ui/forms/scheduled_task.py, functionary/ui/forms/workflow_step.py, functionary/ui/views/build.py, functionary/ui/views/environment/list.py, functionary/ui/views/function.py, functionary/ui/views/scheduled_task/detail.py, functionary/ui/views/scheduled_task/list.py, functionary/ui/views/workflow/list.py
When upgrading to django-tables, we seem to have lost the queryset optimizations adding the related models to the querysets for the list view. This PR adds back the `queryset` definitions.
The details page for Workflows has extra calls but isn't worth the effort to fix it right now.
=> Improve object list queries.

functionary/ui/templates/core/task_detail.html
Rename the id of the parameters `ol` so it doesn't collide with the json task output.
=> Fix the task results clobbering the parameters.

examples/calculator/package.yaml, functionary/builder/models/build.py, functionary/core/api/v1/views/function.py, functionary/core/api/v1/views/package.py, functionary/core/models/__init__.py, functionary/core/models/function.py, functionary/core/models/package.py, functionary/core/models/scheduled_task.py, functionary/core/models/task.py, functionary/core/models/workflow.py, functionary/core/tests/api/v1/views/test_task.py, functionary/core/tests/models/test_function.py, functionary/core/tests/models/test_package.py, functionary/ui/forms/scheduled_task.py, functionary/ui/forms/workflow_step.py, functionary/ui/tests/views/test_function.py, functionary/ui/views/environment/detail.py, functionary/ui/views/function.py, functionary/ui/views/package.py, functionary/ui/views/scheduled_task/create.py, functionary/ui/views/workflow/step/create.py
The UI now filters out inactive Functions as well as active Functions of disabled Packages. When disabling a Package, the Scheduled Tasks for the Functions will also be paused. When enabling a Package, Scheduled Tasks for Functions will *not* be re-activated, this is a manual step.
Disabled Functions do not appear in the Function list when updating an existing Workflow Step or Scheduled Task. When the Package is re-enabled or the Function reactivated, it will show up in those lists again.
There were new tests added to cover these changes. You can manually test these changes out in the UI by starting a Django shell and manually deactivating/activating a Function or disabling/enabling a Package.
```python
from core.models import Package, package
ps = Package.active_objects.all()
ps …
```
=> Filter the UI selection of Functions and Packages to only the active objects.

functionary/ui/templates/builder/build_detail.html, functionary/ui/templates/forms/scheduled_task/scheduled_task_edit.html, functionary/ui/templates/forms/variable_form.html, functionary/ui/templates/forms/workflow/parameter_edit.html, functionary/ui/templates/partials/token.html
Closes #308 
Use slider indicators in favor of check-boxes. Applied everywhere except function Create Task parameters as that is using default templates which were not configurable.
=> #308 - boolean sliders

functionary/ui/templates/base.html, functionary/ui/templates/builder/build_detail.html, functionary/ui/templates/core/function_detail.html, functionary/ui/templates/core/package_detail.html, functionary/ui/templates/core/scheduledtask_detail.html, functionary/ui/templates/core/scheduledtask_list.html, functionary/ui/templates/core/task_detail.html, functionary/ui/templates/core/workflow_detail.html, functionary/ui/templates/core/workflow_list.html, functionary/ui/templates/core/workflow_task.html, functionary/ui/templates/forms/scheduled_task/scheduled_task_edit.html, functionary/ui/views/build.py, functionary/ui/views/function.py, functionary/ui/views/package.py, functionary/ui/views/task.py
Closes #309 
Re-order navbar to have more frequently used items higher up. Change breadcrumb verbiage to match navbar entry.
=> #309 - Change navbar order

functionary/ui/templates/base.html
Closes #322 
When attempting to login with a 3rd party account on the main login page and an error is thrown, the resulting error page had a bad looking nav bar (thin blue line, no contents). It now displays just the Logo and horizontal rule below the logo - nav links are still hidden as user was not authenticated.
=> #322 - Login error navbar fix

functionary/ui/tables/task.py
Closes #327 
Tasking type in Tasking table is now shown as an icon in the Name column instead of its own column.
=> #327 - tasking type icons in table

cli/functionary/package.py, cli/functionary/utils.py, cli/tests/test_package.py, cli/tests/test_utils.py
Closes #190
Checks if there are changes between the package.yaml and the api when publishing. If there are changes it will display the associated changes and ask if you want to continue.
The confirmation can be skipped by adding a -y to the publish command <functionary package publish ~/functionary/examples/demo -y>.
Three Unit tests were added in the cli/tests/tests_utils.py. Further testing can be done by adjusting the package.yaml (ie adding, deleting, changing functions)
=> 190 Add package change confirmation
