beer-garden/functionary

- functionary/builder/utils.py
- functionary/core/api/exceptions.py
- functionary/core/api/mixins.py
- functionary/core/api/v1/serializers/__init__.py
- functionary/core/api/v1/serializers/execute.py
- functionary/core/api/v1/urls.py
- functionary/core/api/v1/views/__init__.py
- functionary/core/api/v1/views/execute.py
- functionary/requirements.in
- functionary/requirements.txt
Added the schema generation to the function creation in the build step.
Added a tasking endpoint to exercise the function parameter validation.
Need to rebase after the team/environment id branch is merged, this is currently hardcoded to a specific environment in my setup.
>  #12 - Confirmed schema, added execute endpoint.

- .github/workflows/linters.yml
- cli/functionary/package.py
- functionary/builder/apps.py
- functionary/builder/tests.py
- functionary/builder/utils.py
- functionary/core/admin/user.py
- functionary/core/tests.py
- functionary/functionary/asgi.py
- functionary/functionary/settings/django_.py
- functionary/functionary/wsgi.py
- functionary/manage.py
- functionary/scheduler/api/v1/serializers/schedule.py
- functionary/scheduler/apps.py
- functionary/scheduler/tests.py
- runner/runner/listener.py
Adds github actions for linting on pull requests.  Also fixes outstanding errors that the linters would have raised.
> GitHub actions

- cli/functionary/config.py
- cli/functionary/login.py
- cli/functionary/package.py
- cli/functionary/tokens.py
Closes #29 
I've duplicated a lot of what we did to store the tokens, though both tokens and the host are now stored in the same config file. I also am trying to stick with camel case for things.
> #29 - Store host after login

- cli/functionary/login.py
- cli/functionary/tokens.py
Closes #52 
Apparently using the centralization for get/post broke login, so I reverted login back to what it was before.
> Issue 52: Make login independent get/post

- cli/functionary/package.py
Closes #59 
Just some small edits to have the language option skip over printing the yaml file and also to make any input name with a '/' stop to give the user better directions.
> Issue 59: Some minor package create cleanup

- functionary/requirements.in
- functionary/requirements.txt
Add django-unicorn to the requirements.txt
> Add django-unicorn dependency

- cli/functionary/package.py
Closes #64 
The behavior Scott and I discussed was having package create simply not do anything if the directory the user wants to access isn't empty. So that's what I've added here
> Issue 64: Check if directory is empty and avoid overwrite

- functionary/.vscode/.debug.env
- functionary/.vscode/launch.json
- runner/.vscode/.debug.env
- runner/.vscode/launch.json
This PR fixes the vscode launch actions that were broken with the recent django settings reorg.
> Fix vscode launch actions

- cli/functionary/client.py
Closes #66 
Wrote a new 400 error handling function for cli/functionary/client.py that should give more user friendly messages for the known types of 400 errors we can come across, and will just pass along the details of the response otherwise.
> Issue 66: Add new error handling function

- functionary/ui/components/env_to_select.py
- functionary/ui/templates/core/package_detail.html
- functionary/ui/views/environments.py
- functionary/ui/views/functions.py
- functionary/ui/views/packages.py
- functionary/ui/views/tasks.py
These changes add `select_related()`s to the `get_queryset()`s used on the UI views to reduce excess database hits.
> 110 task list performance

- functionary/ui/views/builds.py
Optimizations to the DB queries performed by the build list and detail pages.
> #124 - UI: Build view optimizations

- examples/demo/functions.py
- examples/demo/package.yaml
- functionary/ui/templates/core/function_detail.html
Closes #128 
This PR fixes an issue that prevented tasking a function that takes no parameters via the UI.
* Publish the updated demo package
* Task the "variables" function, which now takes now parameters (rather than a dummy parameter that existed as a workaround)
> #128 - Fix issue tasking functions with no parameters

- functionary/ui/templates/partials/modal.html
Adds a modal template to make it easier to create consistently formatted modals.
> UI: Add a modal partial template for consistent formatting

- functionary/core/management/commands/run_scheduler.py
- functionary/functionary/settings/base/logging_.py
Cleaning up some things from the hastily merged scheduler logging PR.
> Scheduler logging cleanup

- cli/README.md
- docs/VSCODE.md
- functionary/README.md
- functionary/builder/templates/builder/docker/javascript.Dockerfile
Minor updates to the READMEs and adding the Dockerfile for javascript packages
> README Updates and javascript Dockerfile

- functionary/builder/tests.py
- functionary/builder/tests/test_utils.py
- functionary/builder/utils.py
- functionary/core/api/v1/views/function.py
- functionary/core/models/function.py
- functionary/core/models/package.py
- functionary/core/models/scheduled_task.py
- functionary/core/models/task.py
- functionary/core/tests/models/test_function.py
- functionary/core/tests/models/test_task.py
- functionary/ui/forms/scheduled_task.py
- functionary/ui/templates/core/function_detail.html
- functionary/ui/templates/core/package_detail.html
- functionary/ui/views/functions.py
Closes #127
The main objective of this PR is to add the active field to the function model. The functions listed in the package should reflect only the ones listed in the package.yaml.
**Testing Instructions**
A unit test has been added to test the deactivation feature in the function.
Verify that the only functions that appear in the package UI are the ones in the yaml.
In addition, the drop down list to schedule should only have the active functions as options.
The inactive functions should cause scheduled tasks related to that function to be paused.
Verify the inactive functions detail page do not have an execute button and should have a banner saying its deactivated
Removing a function from the yaml should result in any scheduled tasks associated to be paused, although that function …
> #127 - Add active field to functions #127

- functionary.code-workspace
- functionary/.vscode/tasks.json
Some changes to the vscode tasks to make the uid for the image get properly set to that of the local user.
> Update compose up vscode task to properly set the docker image uid

- functionary/ui/static/css/functionary.css
- functionary/ui/templates/core/function_detail.html
- functionary/ui/templates/core/scheduledtask_detail.html
- functionary/ui/templates/core/task_detail.html
Closes #287 
Pretty print JSON Parameters whenever they appear (not in tables). Adjusted green color ever so slightly to have a compliant contrast ratio to white.
> #287 - pretty print parameters

- functionary/ui/static/css/functionary.css
- functionary/ui/templates/builder/build_detail.html
- functionary/ui/templates/core/scheduledtask_detail.html
- functionary/ui/templates/core/task_detail.html
Closes #297 
Add color indicators for status of build and task on their detail pages
> #297 -Status indicator colors

- functionary/ui/templates/core/function_detail.html
- functionary/ui/templates/core/workflow_task.html
Closes #295 
Schema sections no longer desired.
> #295 - Remove schema sections

- functionary/ui/templates/account/login.html
Closes #315 
Login card was not centered for some reason. Also a little too wide on "wide" screen
> #315 - center login

- functionary/ui/tables/schedule_task.py
Closes #311 
No longer link to individual function page in table
> #311 - remove function link in schedule table
